Section "InputClass"
  Identifier "My Zowie Mouse"
  Driver "libinput"
  MatchProduct "BenQ ZOWIE BenQ ZOWIE Gaming Mouse"
  MatchIsPointer "on"
  Option "AccelProfile" "flat"
  Option "TransformationMatrix" "0.55 0 0 0 0.55 0 0 0 1"
EndSection
