# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0e87d930-b0c0-41f3-a254-6d579bdd2d4f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0e87d930-b0c0-41f3-a254-6d579bdd2d4f".device = "/dev/disk/by-uuid/0e87d930-b0c0-41f3-a254-6d579bdd2d4f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/03A7-8732";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
